# Calico Version v3.13.3
# https://docs.projectcalico.org/releases#v3.13.3
# This manifest includes the following component versions:
#   calico/ctl:v3.13.3

apiVersion: v1
kind: ServiceAccount
metadata:
  name: ip-exporter
  namespace: monitoring



---

kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: ip-exporter
rules:
  - apiGroups: [""]
    resources:
      - namespaces
      - nodes
    verbs:
      - get
      - list
  - apiGroups: [""]
    resources:
      - pods
      - serviceaccounts
    verbs:
      - get
      - list
  - apiGroups: ["crd.projectcalico.org"]
    resources:
      - bgppeers
      - bgpconfigurations
      - clusterinformations
      - felixconfigurations
      - globalnetworkpolicies
      - globalnetworksets
      - ippools
      - networkpolicies
      - networksets
      - hostendpoints
      - ipamblocks
      - blockaffinities
      - ipamhandles
    verbs:
      - get
      - list
---

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: ip-exporter
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ip-exporter
subjects:
  - kind: ServiceAccount
    name: ip-exporter
    namespace: monitoring


---
apiVersion: v1
kind: Service
metadata:
  name: ip-exporter-svc
  namespace: monitoring
spec:
  ports:
    - name: metrics-port
      port: 9324
      protocol: TCP
      targetPort: 9324
  selector:
    k8s-app: ip-exporter
---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: ip-exporter
  name: ip-exporter
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: ip-exporter
  template:
    metadata:
      labels:
        k8s-app: ip-exporter
    spec:
      nodeSelector:
        kubernetes.io/os: linux
      serviceAccountName: ip-exporter
      containers:
        - name: ip-exporter
          image: 10.10.101.175/k8s-deploy/ip-exporter:1.0
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
          ports:
            - containerPort: 9324
              name: metrics
          env:
            - name: DATASTORE_TYPE
              value: kubernetes